// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmsProto.proto

package com.mservice.momo.msg;

public final class SmsProto {
  private SmsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.mservice.momo.msg.MsgType}
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ERR = 1;</code>
     */
    ERR(0, 1),
    /**
     * <code>APP_SMS_REQUEST = 2;</code>
     */
    APP_SMS_REQUEST(1, 2),
    /**
     * <code>APP_SMS_REPLY = 3;</code>
     */
    APP_SMS_REPLY(2, 3),
    /**
     * <code>ACK = 4;</code>
     */
    ACK(3, 4),
    /**
     * <code>MUA123_REQUEST = 5;</code>
     */
    MUA123_REQUEST(4, 5),
    ;

    /**
     * <code>ERR = 1;</code>
     */
    public static final int ERR_VALUE = 1;
    /**
     * <code>APP_SMS_REQUEST = 2;</code>
     */
    public static final int APP_SMS_REQUEST_VALUE = 2;
    /**
     * <code>APP_SMS_REPLY = 3;</code>
     */
    public static final int APP_SMS_REPLY_VALUE = 3;
    /**
     * <code>ACK = 4;</code>
     */
    public static final int ACK_VALUE = 4;
    /**
     * <code>MUA123_REQUEST = 5;</code>
     */
    public static final int MUA123_REQUEST_VALUE = 5;


    public final int getNumber() { return value; }

    public static MsgType valueOf(int value) {
      switch (value) {
        case 1: return ERR;
        case 2: return APP_SMS_REQUEST;
        case 3: return APP_SMS_REPLY;
        case 4: return ACK;
        case 5: return MUA123_REQUEST;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.mservice.momo.msg.SmsProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MsgType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.mservice.momo.msg.MsgType)
  }

  public interface ErrOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint32 rcode = 1;
    /**
     * <code>optional uint32 rcode = 1;</code>
     */
    boolean hasRcode();
    /**
     * <code>optional uint32 rcode = 1;</code>
     */
    int getRcode();

    // optional string rdesc = 2;
    /**
     * <code>optional string rdesc = 2;</code>
     */
    boolean hasRdesc();
    /**
     * <code>optional string rdesc = 2;</code>
     */
    java.lang.String getRdesc();
    /**
     * <code>optional string rdesc = 2;</code>
     */
    com.google.protobuf.ByteString
        getRdescBytes();
  }
  /**
   * Protobuf type {@code com.mservice.momo.msg.Err}
   */
  public static final class Err extends
      com.google.protobuf.GeneratedMessage
      implements ErrOrBuilder {
    // Use Err.newBuilder() to construct.
    private Err(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Err(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Err defaultInstance;
    public static Err getDefaultInstance() {
      return defaultInstance;
    }

    public Err getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Err(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rcode_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              rdesc_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mservice.momo.msg.SmsProto.internal_static_com_mservice_momo_msg_Err_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mservice.momo.msg.SmsProto.internal_static_com_mservice_momo_msg_Err_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mservice.momo.msg.SmsProto.Err.class, com.mservice.momo.msg.SmsProto.Err.Builder.class);
    }

    public static com.google.protobuf.Parser<Err> PARSER =
        new com.google.protobuf.AbstractParser<Err>() {
      public Err parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Err(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Err> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.mservice.momo.msg.Err.ResultCode}
     */
    public enum ResultCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MSG_FORMAT_NOT_CORRECT = 1;</code>
       */
      MSG_FORMAT_NOT_CORRECT(0, 1),
      /**
       * <code>NUMBER_NOT_VALID = 2;</code>
       */
      NUMBER_NOT_VALID(1, 2),
      /**
       * <code>PIN_NOT_VALID = 3;</code>
       */
      PIN_NOT_VALID(2, 3),
      ;

      /**
       * <code>MSG_FORMAT_NOT_CORRECT = 1;</code>
       */
      public static final int MSG_FORMAT_NOT_CORRECT_VALUE = 1;
      /**
       * <code>NUMBER_NOT_VALID = 2;</code>
       */
      public static final int NUMBER_NOT_VALID_VALUE = 2;
      /**
       * <code>PIN_NOT_VALID = 3;</code>
       */
      public static final int PIN_NOT_VALID_VALUE = 3;


      public final int getNumber() { return value; }

      public static ResultCode valueOf(int value) {
        switch (value) {
          case 1: return MSG_FORMAT_NOT_CORRECT;
          case 2: return NUMBER_NOT_VALID;
          case 3: return PIN_NOT_VALID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResultCode>() {
              public ResultCode findValueByNumber(int number) {
                return ResultCode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.mservice.momo.msg.SmsProto.Err.getDescriptor().getEnumTypes().get(0);
      }

      private static final ResultCode[] VALUES = values();

      public static ResultCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ResultCode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.mservice.momo.msg.Err.ResultCode)
    }

    private int bitField0_;
    // optional uint32 rcode = 1;
    public static final int RCODE_FIELD_NUMBER = 1;
    private int rcode_;
    /**
     * <code>optional uint32 rcode = 1;</code>
     */
    public boolean hasRcode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 rcode = 1;</code>
     */
    public int getRcode() {
      return rcode_;
    }

    // optional string rdesc = 2;
    public static final int RDESC_FIELD_NUMBER = 2;
    private java.lang.Object rdesc_;
    /**
     * <code>optional string rdesc = 2;</code>
     */
    public boolean hasRdesc() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string rdesc = 2;</code>
     */
    public java.lang.String getRdesc() {
      java.lang.Object ref = rdesc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          rdesc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string rdesc = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRdescBytes() {
      java.lang.Object ref = rdesc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rdesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      rcode_ = 0;
      rdesc_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, rcode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRdescBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, rcode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRdescBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mservice.momo.msg.SmsProto.Err parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mservice.momo.msg.SmsProto.Err parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mservice.momo.msg.SmsProto.Err parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mservice.momo.msg.SmsProto.Err parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mservice.momo.msg.SmsProto.Err parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mservice.momo.msg.SmsProto.Err parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mservice.momo.msg.SmsProto.Err parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mservice.momo.msg.SmsProto.Err parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mservice.momo.msg.SmsProto.Err parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mservice.momo.msg.SmsProto.Err parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mservice.momo.msg.SmsProto.Err prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mservice.momo.msg.Err}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mservice.momo.msg.SmsProto.ErrOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mservice.momo.msg.SmsProto.internal_static_com_mservice_momo_msg_Err_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mservice.momo.msg.SmsProto.internal_static_com_mservice_momo_msg_Err_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mservice.momo.msg.SmsProto.Err.class, com.mservice.momo.msg.SmsProto.Err.Builder.class);
      }

      // Construct using com.mservice.momo.msg.SmsProto.Err.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rcode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        rdesc_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mservice.momo.msg.SmsProto.internal_static_com_mservice_momo_msg_Err_descriptor;
      }

      public com.mservice.momo.msg.SmsProto.Err getDefaultInstanceForType() {
        return com.mservice.momo.msg.SmsProto.Err.getDefaultInstance();
      }

      public com.mservice.momo.msg.SmsProto.Err build() {
        com.mservice.momo.msg.SmsProto.Err result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mservice.momo.msg.SmsProto.Err buildPartial() {
        com.mservice.momo.msg.SmsProto.Err result = new com.mservice.momo.msg.SmsProto.Err(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rcode_ = rcode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rdesc_ = rdesc_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mservice.momo.msg.SmsProto.Err) {
          return mergeFrom((com.mservice.momo.msg.SmsProto.Err)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mservice.momo.msg.SmsProto.Err other) {
        if (other == com.mservice.momo.msg.SmsProto.Err.getDefaultInstance()) return this;
        if (other.hasRcode()) {
          setRcode(other.getRcode());
        }
        if (other.hasRdesc()) {
          bitField0_ |= 0x00000002;
          rdesc_ = other.rdesc_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mservice.momo.msg.SmsProto.Err parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mservice.momo.msg.SmsProto.Err) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint32 rcode = 1;
      private int rcode_ ;
      /**
       * <code>optional uint32 rcode = 1;</code>
       */
      public boolean hasRcode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 rcode = 1;</code>
       */
      public int getRcode() {
        return rcode_;
      }
      /**
       * <code>optional uint32 rcode = 1;</code>
       */
      public Builder setRcode(int value) {
        bitField0_ |= 0x00000001;
        rcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 rcode = 1;</code>
       */
      public Builder clearRcode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rcode_ = 0;
        onChanged();
        return this;
      }

      // optional string rdesc = 2;
      private java.lang.Object rdesc_ = "";
      /**
       * <code>optional string rdesc = 2;</code>
       */
      public boolean hasRdesc() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string rdesc = 2;</code>
       */
      public java.lang.String getRdesc() {
        java.lang.Object ref = rdesc_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          rdesc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string rdesc = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRdescBytes() {
        java.lang.Object ref = rdesc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rdesc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string rdesc = 2;</code>
       */
      public Builder setRdesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        rdesc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string rdesc = 2;</code>
       */
      public Builder clearRdesc() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rdesc_ = getDefaultInstance().getRdesc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string rdesc = 2;</code>
       */
      public Builder setRdescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        rdesc_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mservice.momo.msg.Err)
    }

    static {
      defaultInstance = new Err(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mservice.momo.msg.Err)
  }

  public interface SmsRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string rsa_content = 1;
    /**
     * <code>optional string rsa_content = 1;</code>
     */
    boolean hasRsaContent();
    /**
     * <code>optional string rsa_content = 1;</code>
     */
    java.lang.String getRsaContent();
    /**
     * <code>optional string rsa_content = 1;</code>
     */
    com.google.protobuf.ByteString
        getRsaContentBytes();
  }
  /**
   * Protobuf type {@code com.mservice.momo.msg.SmsRequest}
   *
   * <pre>
   *for internal only
   * </pre>
   */
  public static final class SmsRequest extends
      com.google.protobuf.GeneratedMessage
      implements SmsRequestOrBuilder {
    // Use SmsRequest.newBuilder() to construct.
    private SmsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SmsRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SmsRequest defaultInstance;
    public static SmsRequest getDefaultInstance() {
      return defaultInstance;
    }

    public SmsRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SmsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              rsaContent_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mservice.momo.msg.SmsProto.internal_static_com_mservice_momo_msg_SmsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mservice.momo.msg.SmsProto.internal_static_com_mservice_momo_msg_SmsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mservice.momo.msg.SmsProto.SmsRequest.class, com.mservice.momo.msg.SmsProto.SmsRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<SmsRequest> PARSER =
        new com.google.protobuf.AbstractParser<SmsRequest>() {
      public SmsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SmsRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SmsRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string rsa_content = 1;
    public static final int RSA_CONTENT_FIELD_NUMBER = 1;
    private java.lang.Object rsaContent_;
    /**
     * <code>optional string rsa_content = 1;</code>
     */
    public boolean hasRsaContent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string rsa_content = 1;</code>
     */
    public java.lang.String getRsaContent() {
      java.lang.Object ref = rsaContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          rsaContent_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string rsa_content = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRsaContentBytes() {
      java.lang.Object ref = rsaContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rsaContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      rsaContent_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRsaContentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRsaContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mservice.momo.msg.SmsProto.SmsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mservice.momo.msg.SmsProto.SmsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mservice.momo.msg.SmsProto.SmsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mservice.momo.msg.SmsProto.SmsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mservice.momo.msg.SmsProto.SmsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mservice.momo.msg.SmsProto.SmsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mservice.momo.msg.SmsProto.SmsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mservice.momo.msg.SmsProto.SmsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mservice.momo.msg.SmsProto.SmsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mservice.momo.msg.SmsProto.SmsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mservice.momo.msg.SmsProto.SmsRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mservice.momo.msg.SmsRequest}
     *
     * <pre>
     *for internal only
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mservice.momo.msg.SmsProto.SmsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mservice.momo.msg.SmsProto.internal_static_com_mservice_momo_msg_SmsRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mservice.momo.msg.SmsProto.internal_static_com_mservice_momo_msg_SmsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mservice.momo.msg.SmsProto.SmsRequest.class, com.mservice.momo.msg.SmsProto.SmsRequest.Builder.class);
      }

      // Construct using com.mservice.momo.msg.SmsProto.SmsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rsaContent_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mservice.momo.msg.SmsProto.internal_static_com_mservice_momo_msg_SmsRequest_descriptor;
      }

      public com.mservice.momo.msg.SmsProto.SmsRequest getDefaultInstanceForType() {
        return com.mservice.momo.msg.SmsProto.SmsRequest.getDefaultInstance();
      }

      public com.mservice.momo.msg.SmsProto.SmsRequest build() {
        com.mservice.momo.msg.SmsProto.SmsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mservice.momo.msg.SmsProto.SmsRequest buildPartial() {
        com.mservice.momo.msg.SmsProto.SmsRequest result = new com.mservice.momo.msg.SmsProto.SmsRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rsaContent_ = rsaContent_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mservice.momo.msg.SmsProto.SmsRequest) {
          return mergeFrom((com.mservice.momo.msg.SmsProto.SmsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mservice.momo.msg.SmsProto.SmsRequest other) {
        if (other == com.mservice.momo.msg.SmsProto.SmsRequest.getDefaultInstance()) return this;
        if (other.hasRsaContent()) {
          bitField0_ |= 0x00000001;
          rsaContent_ = other.rsaContent_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mservice.momo.msg.SmsProto.SmsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mservice.momo.msg.SmsProto.SmsRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string rsa_content = 1;
      private java.lang.Object rsaContent_ = "";
      /**
       * <code>optional string rsa_content = 1;</code>
       */
      public boolean hasRsaContent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string rsa_content = 1;</code>
       */
      public java.lang.String getRsaContent() {
        java.lang.Object ref = rsaContent_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          rsaContent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string rsa_content = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRsaContentBytes() {
        java.lang.Object ref = rsaContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rsaContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string rsa_content = 1;</code>
       */
      public Builder setRsaContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rsaContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string rsa_content = 1;</code>
       */
      public Builder clearRsaContent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rsaContent_ = getDefaultInstance().getRsaContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string rsa_content = 1;</code>
       */
      public Builder setRsaContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rsaContent_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mservice.momo.msg.SmsRequest)
    }

    static {
      defaultInstance = new SmsRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mservice.momo.msg.SmsRequest)
  }

  public interface SmsReplyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bool result = 1;
    /**
     * <code>optional bool result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>optional bool result = 1;</code>
     */
    boolean getResult();

    // optional uint32 rcode = 2;
    /**
     * <code>optional uint32 rcode = 2;</code>
     */
    boolean hasRcode();
    /**
     * <code>optional uint32 rcode = 2;</code>
     */
    int getRcode();
  }
  /**
   * Protobuf type {@code com.mservice.momo.msg.SmsReply}
   */
  public static final class SmsReply extends
      com.google.protobuf.GeneratedMessage
      implements SmsReplyOrBuilder {
    // Use SmsReply.newBuilder() to construct.
    private SmsReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SmsReply(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SmsReply defaultInstance;
    public static SmsReply getDefaultInstance() {
      return defaultInstance;
    }

    public SmsReply getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SmsReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              rcode_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mservice.momo.msg.SmsProto.internal_static_com_mservice_momo_msg_SmsReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mservice.momo.msg.SmsProto.internal_static_com_mservice_momo_msg_SmsReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mservice.momo.msg.SmsProto.SmsReply.class, com.mservice.momo.msg.SmsProto.SmsReply.Builder.class);
    }

    public static com.google.protobuf.Parser<SmsReply> PARSER =
        new com.google.protobuf.AbstractParser<SmsReply>() {
      public SmsReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SmsReply(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SmsReply> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bool result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private boolean result_;
    /**
     * <code>optional bool result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool result = 1;</code>
     */
    public boolean getResult() {
      return result_;
    }

    // optional uint32 rcode = 2;
    public static final int RCODE_FIELD_NUMBER = 2;
    private int rcode_;
    /**
     * <code>optional uint32 rcode = 2;</code>
     */
    public boolean hasRcode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 rcode = 2;</code>
     */
    public int getRcode() {
      return rcode_;
    }

    private void initFields() {
      result_ = false;
      rcode_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, rcode_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, rcode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mservice.momo.msg.SmsProto.SmsReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mservice.momo.msg.SmsProto.SmsReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mservice.momo.msg.SmsProto.SmsReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mservice.momo.msg.SmsProto.SmsReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mservice.momo.msg.SmsProto.SmsReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mservice.momo.msg.SmsProto.SmsReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mservice.momo.msg.SmsProto.SmsReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mservice.momo.msg.SmsProto.SmsReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mservice.momo.msg.SmsProto.SmsReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mservice.momo.msg.SmsProto.SmsReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mservice.momo.msg.SmsProto.SmsReply prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mservice.momo.msg.SmsReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mservice.momo.msg.SmsProto.SmsReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mservice.momo.msg.SmsProto.internal_static_com_mservice_momo_msg_SmsReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mservice.momo.msg.SmsProto.internal_static_com_mservice_momo_msg_SmsReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mservice.momo.msg.SmsProto.SmsReply.class, com.mservice.momo.msg.SmsProto.SmsReply.Builder.class);
      }

      // Construct using com.mservice.momo.msg.SmsProto.SmsReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        rcode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mservice.momo.msg.SmsProto.internal_static_com_mservice_momo_msg_SmsReply_descriptor;
      }

      public com.mservice.momo.msg.SmsProto.SmsReply getDefaultInstanceForType() {
        return com.mservice.momo.msg.SmsProto.SmsReply.getDefaultInstance();
      }

      public com.mservice.momo.msg.SmsProto.SmsReply build() {
        com.mservice.momo.msg.SmsProto.SmsReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mservice.momo.msg.SmsProto.SmsReply buildPartial() {
        com.mservice.momo.msg.SmsProto.SmsReply result = new com.mservice.momo.msg.SmsProto.SmsReply(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rcode_ = rcode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mservice.momo.msg.SmsProto.SmsReply) {
          return mergeFrom((com.mservice.momo.msg.SmsProto.SmsReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mservice.momo.msg.SmsProto.SmsReply other) {
        if (other == com.mservice.momo.msg.SmsProto.SmsReply.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasRcode()) {
          setRcode(other.getRcode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mservice.momo.msg.SmsProto.SmsReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mservice.momo.msg.SmsProto.SmsReply) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bool result = 1;
      private boolean result_ ;
      /**
       * <code>optional bool result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool result = 1;</code>
       */
      public boolean getResult() {
        return result_;
      }
      /**
       * <code>optional bool result = 1;</code>
       */
      public Builder setResult(boolean value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = false;
        onChanged();
        return this;
      }

      // optional uint32 rcode = 2;
      private int rcode_ ;
      /**
       * <code>optional uint32 rcode = 2;</code>
       */
      public boolean hasRcode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 rcode = 2;</code>
       */
      public int getRcode() {
        return rcode_;
      }
      /**
       * <code>optional uint32 rcode = 2;</code>
       */
      public Builder setRcode(int value) {
        bitField0_ |= 0x00000002;
        rcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 rcode = 2;</code>
       */
      public Builder clearRcode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rcode_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mservice.momo.msg.SmsReply)
    }

    static {
      defaultInstance = new SmsReply(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mservice.momo.msg.SmsReply)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mservice_momo_msg_Err_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mservice_momo_msg_Err_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mservice_momo_msg_SmsRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mservice_momo_msg_SmsRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mservice_momo_msg_SmsReply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mservice_momo_msg_SmsReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016SmsProto.proto\022\025com.mservice.momo.msg\"" +
      "v\n\003Err\022\r\n\005rcode\030\001 \001(\r\022\r\n\005rdesc\030\002 \001(\t\"Q\n\n" +
      "ResultCode\022\032\n\026MSG_FORMAT_NOT_CORRECT\020\001\022\024" +
      "\n\020NUMBER_NOT_VALID\020\002\022\021\n\rPIN_NOT_VALID\020\003\"" +
      "!\n\nSmsRequest\022\023\n\013rsa_content\030\001 \001(\t\")\n\010Sm" +
      "sReply\022\016\n\006result\030\001 \001(\010\022\r\n\005rcode\030\002 \001(\r*W\n" +
      "\007MsgType\022\007\n\003ERR\020\001\022\023\n\017APP_SMS_REQUEST\020\002\022\021" +
      "\n\rAPP_SMS_REPLY\020\003\022\007\n\003ACK\020\004\022\022\n\016MUA123_REQ" +
      "UEST\020\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_mservice_momo_msg_Err_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_mservice_momo_msg_Err_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mservice_momo_msg_Err_descriptor,
              new java.lang.String[] { "Rcode", "Rdesc", });
          internal_static_com_mservice_momo_msg_SmsRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_mservice_momo_msg_SmsRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mservice_momo_msg_SmsRequest_descriptor,
              new java.lang.String[] { "RsaContent", });
          internal_static_com_mservice_momo_msg_SmsReply_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_mservice_momo_msg_SmsReply_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mservice_momo_msg_SmsReply_descriptor,
              new java.lang.String[] { "Result", "Rcode", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
