// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StatisticModels.proto

package com.mservice.momo.msg;

public final class StatisticModels {
  private StatisticModels() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.mservice.momo.msg.SubActionType}
   */
  public enum SubActionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>REGISTER_FROM_WEB_IN_DAY = 1;</code>
     */
    REGISTER_FROM_WEB_IN_DAY(0, 1),
    /**
     * <code>REGISTER_FROM_PHONE_IN_DAY = 2;</code>
     */
    REGISTER_FROM_PHONE_IN_DAY(1, 2),
    /**
     * <code>NEW_WEB_USER_LOGIN_IN_DAY = 3;</code>
     *
     * <pre>
     * số người lần đầu đăng nhập trên web. (có thể sum để ra tháng)
     * </pre>
     */
    NEW_WEB_USER_LOGIN_IN_DAY(2, 3),
    /**
     * <code>NEW_PHONE_USER_LOGIN_IN_DAY = 4;</code>
     *
     * <pre>
     * số người lần đầu đăng nhập trên phone. (có thể sum để ra tháng)
     * </pre>
     */
    NEW_PHONE_USER_LOGIN_IN_DAY(3, 4),
    /**
     * <code>USER_LOGIN_WEB_IN_DAY = 5;</code>
     *
     * <pre>
     * số người đăng nhập trên web trong ngày.
     * </pre>
     */
    USER_LOGIN_WEB_IN_DAY(4, 5),
    /**
     * <code>USER_LOGIN_PHONE_IN_DAY = 6;</code>
     *
     * <pre>
     * số người đăng nhập trên phone trong ngày.
     * </pre>
     */
    USER_LOGIN_PHONE_IN_DAY(5, 6),
    /**
     * <code>WEB_USER_HAS_TRANS_IN_DAY = 7;</code>
     *
     * <pre>
     * số người có giao dịch trong ngày.
     * </pre>
     */
    WEB_USER_HAS_TRANS_IN_DAY(6, 7),
    /**
     * <code>WEB_USER_HAS_TRANS_IN_MONTH = 8;</code>
     *
     * <pre>
     * số người có giao dịch trong tháng.
     * </pre>
     */
    WEB_USER_HAS_TRANS_IN_MONTH(7, 8),
    /**
     * <code>MOBILE_USER_HAS_TRANS_IN_DAY = 9;</code>
     *
     * <pre>
     * số người có giao dịch trong ngày.
     * </pre>
     */
    MOBILE_USER_HAS_TRANS_IN_DAY(8, 9),
    /**
     * <code>MOBILE_USER_HAS_TRANS_IN_MONTH = 10;</code>
     *
     * <pre>
     * số người có giao dịch trong tháng.
     * </pre>
     */
    MOBILE_USER_HAS_TRANS_IN_MONTH(9, 10),
    /**
     * <code>MAX_WEB_ONLINE_USER_IN_DAY = 12;</code>
     *
     * <pre>
     * thời điểm và số người online trên web lớn nhất trong ngày
     * </pre>
     */
    MAX_WEB_ONLINE_USER_IN_DAY(10, 12),
    /**
     * <code>MAX_PHONE_ONLINE_USER_IN_DAY = 13;</code>
     *
     * <pre>
     * thời điểm và số người online trên phone lớn nhất trong ngày
     * </pre>
     */
    MAX_PHONE_ONLINE_USER_IN_DAY(11, 13),
    /**
     * <code>SEND_NOTI_VIA_SOCKET_IN_DAY = 14;</code>
     */
    SEND_NOTI_VIA_SOCKET_IN_DAY(12, 14),
    /**
     * <code>SEND_NOTI_VIA_CLOUD_IN_DAY = 15;</code>
     */
    SEND_NOTI_VIA_CLOUD_IN_DAY(13, 15),
    /**
     * <code>SEND_NOTI_LIST_VIA_SOCKET_IN_DAY = 16;</code>
     */
    SEND_NOTI_LIST_VIA_SOCKET_IN_DAY(14, 16),
    /**
     * <code>SEND_NOTI_LIST_VIA_CLOUD_IN_DAY = 17;</code>
     */
    SEND_NOTI_LIST_VIA_CLOUD_IN_DAY(15, 17),
    ;

    /**
     * <code>REGISTER_FROM_WEB_IN_DAY = 1;</code>
     */
    public static final int REGISTER_FROM_WEB_IN_DAY_VALUE = 1;
    /**
     * <code>REGISTER_FROM_PHONE_IN_DAY = 2;</code>
     */
    public static final int REGISTER_FROM_PHONE_IN_DAY_VALUE = 2;
    /**
     * <code>NEW_WEB_USER_LOGIN_IN_DAY = 3;</code>
     *
     * <pre>
     * số người lần đầu đăng nhập trên web. (có thể sum để ra tháng)
     * </pre>
     */
    public static final int NEW_WEB_USER_LOGIN_IN_DAY_VALUE = 3;
    /**
     * <code>NEW_PHONE_USER_LOGIN_IN_DAY = 4;</code>
     *
     * <pre>
     * số người lần đầu đăng nhập trên phone. (có thể sum để ra tháng)
     * </pre>
     */
    public static final int NEW_PHONE_USER_LOGIN_IN_DAY_VALUE = 4;
    /**
     * <code>USER_LOGIN_WEB_IN_DAY = 5;</code>
     *
     * <pre>
     * số người đăng nhập trên web trong ngày.
     * </pre>
     */
    public static final int USER_LOGIN_WEB_IN_DAY_VALUE = 5;
    /**
     * <code>USER_LOGIN_PHONE_IN_DAY = 6;</code>
     *
     * <pre>
     * số người đăng nhập trên phone trong ngày.
     * </pre>
     */
    public static final int USER_LOGIN_PHONE_IN_DAY_VALUE = 6;
    /**
     * <code>WEB_USER_HAS_TRANS_IN_DAY = 7;</code>
     *
     * <pre>
     * số người có giao dịch trong ngày.
     * </pre>
     */
    public static final int WEB_USER_HAS_TRANS_IN_DAY_VALUE = 7;
    /**
     * <code>WEB_USER_HAS_TRANS_IN_MONTH = 8;</code>
     *
     * <pre>
     * số người có giao dịch trong tháng.
     * </pre>
     */
    public static final int WEB_USER_HAS_TRANS_IN_MONTH_VALUE = 8;
    /**
     * <code>MOBILE_USER_HAS_TRANS_IN_DAY = 9;</code>
     *
     * <pre>
     * số người có giao dịch trong ngày.
     * </pre>
     */
    public static final int MOBILE_USER_HAS_TRANS_IN_DAY_VALUE = 9;
    /**
     * <code>MOBILE_USER_HAS_TRANS_IN_MONTH = 10;</code>
     *
     * <pre>
     * số người có giao dịch trong tháng.
     * </pre>
     */
    public static final int MOBILE_USER_HAS_TRANS_IN_MONTH_VALUE = 10;
    /**
     * <code>MAX_WEB_ONLINE_USER_IN_DAY = 12;</code>
     *
     * <pre>
     * thời điểm và số người online trên web lớn nhất trong ngày
     * </pre>
     */
    public static final int MAX_WEB_ONLINE_USER_IN_DAY_VALUE = 12;
    /**
     * <code>MAX_PHONE_ONLINE_USER_IN_DAY = 13;</code>
     *
     * <pre>
     * thời điểm và số người online trên phone lớn nhất trong ngày
     * </pre>
     */
    public static final int MAX_PHONE_ONLINE_USER_IN_DAY_VALUE = 13;
    /**
     * <code>SEND_NOTI_VIA_SOCKET_IN_DAY = 14;</code>
     */
    public static final int SEND_NOTI_VIA_SOCKET_IN_DAY_VALUE = 14;
    /**
     * <code>SEND_NOTI_VIA_CLOUD_IN_DAY = 15;</code>
     */
    public static final int SEND_NOTI_VIA_CLOUD_IN_DAY_VALUE = 15;
    /**
     * <code>SEND_NOTI_LIST_VIA_SOCKET_IN_DAY = 16;</code>
     */
    public static final int SEND_NOTI_LIST_VIA_SOCKET_IN_DAY_VALUE = 16;
    /**
     * <code>SEND_NOTI_LIST_VIA_CLOUD_IN_DAY = 17;</code>
     */
    public static final int SEND_NOTI_LIST_VIA_CLOUD_IN_DAY_VALUE = 17;


    public final int getNumber() { return value; }

    public static SubActionType valueOf(int value) {
      switch (value) {
        case 1: return REGISTER_FROM_WEB_IN_DAY;
        case 2: return REGISTER_FROM_PHONE_IN_DAY;
        case 3: return NEW_WEB_USER_LOGIN_IN_DAY;
        case 4: return NEW_PHONE_USER_LOGIN_IN_DAY;
        case 5: return USER_LOGIN_WEB_IN_DAY;
        case 6: return USER_LOGIN_PHONE_IN_DAY;
        case 7: return WEB_USER_HAS_TRANS_IN_DAY;
        case 8: return WEB_USER_HAS_TRANS_IN_MONTH;
        case 9: return MOBILE_USER_HAS_TRANS_IN_DAY;
        case 10: return MOBILE_USER_HAS_TRANS_IN_MONTH;
        case 12: return MAX_WEB_ONLINE_USER_IN_DAY;
        case 13: return MAX_PHONE_ONLINE_USER_IN_DAY;
        case 14: return SEND_NOTI_VIA_SOCKET_IN_DAY;
        case 15: return SEND_NOTI_VIA_CLOUD_IN_DAY;
        case 16: return SEND_NOTI_LIST_VIA_SOCKET_IN_DAY;
        case 17: return SEND_NOTI_LIST_VIA_CLOUD_IN_DAY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SubActionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<SubActionType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SubActionType>() {
            public SubActionType findValueByNumber(int number) {
              return SubActionType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.mservice.momo.msg.StatisticModels.getDescriptor().getEnumTypes().get(0);
    }

    private static final SubActionType[] VALUES = values();

    public static SubActionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private SubActionType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.mservice.momo.msg.SubActionType)
  }

  /**
   * Protobuf enum {@code com.mservice.momo.msg.ActionType}
   */
  public enum ActionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>USER_REGISTER = 100;</code>
     */
    USER_REGISTER(0, 100),
    /**
     * <code>USER_LOGIN = 101;</code>
     */
    USER_LOGIN(1, 101),
    /**
     * <code>USER_TRANS = 102;</code>
     */
    USER_TRANS(2, 102),
    /**
     * <code>USER_ONLINE = 103;</code>
     */
    USER_ONLINE(3, 103),
    /**
     * <code>USER_OFFLINE = 104;</code>
     */
    USER_OFFLINE(4, 104),
    /**
     * <code>SEND_NOTI_VIA_SOCKET = 105;</code>
     */
    SEND_NOTI_VIA_SOCKET(5, 105),
    /**
     * <code>SEND_NOTI_VIA_CLOUD = 106;</code>
     */
    SEND_NOTI_VIA_CLOUD(6, 106),
    /**
     * <code>SEND_NOTI_LIST_VIA_SOCKET = 107;</code>
     */
    SEND_NOTI_LIST_VIA_SOCKET(7, 107),
    /**
     * <code>SEND_NOTI_LIST_VIA_CLOUD = 108;</code>
     */
    SEND_NOTI_LIST_VIA_CLOUD(8, 108),
    ;

    /**
     * <code>USER_REGISTER = 100;</code>
     */
    public static final int USER_REGISTER_VALUE = 100;
    /**
     * <code>USER_LOGIN = 101;</code>
     */
    public static final int USER_LOGIN_VALUE = 101;
    /**
     * <code>USER_TRANS = 102;</code>
     */
    public static final int USER_TRANS_VALUE = 102;
    /**
     * <code>USER_ONLINE = 103;</code>
     */
    public static final int USER_ONLINE_VALUE = 103;
    /**
     * <code>USER_OFFLINE = 104;</code>
     */
    public static final int USER_OFFLINE_VALUE = 104;
    /**
     * <code>SEND_NOTI_VIA_SOCKET = 105;</code>
     */
    public static final int SEND_NOTI_VIA_SOCKET_VALUE = 105;
    /**
     * <code>SEND_NOTI_VIA_CLOUD = 106;</code>
     */
    public static final int SEND_NOTI_VIA_CLOUD_VALUE = 106;
    /**
     * <code>SEND_NOTI_LIST_VIA_SOCKET = 107;</code>
     */
    public static final int SEND_NOTI_LIST_VIA_SOCKET_VALUE = 107;
    /**
     * <code>SEND_NOTI_LIST_VIA_CLOUD = 108;</code>
     */
    public static final int SEND_NOTI_LIST_VIA_CLOUD_VALUE = 108;


    public final int getNumber() { return value; }

    public static ActionType valueOf(int value) {
      switch (value) {
        case 100: return USER_REGISTER;
        case 101: return USER_LOGIN;
        case 102: return USER_TRANS;
        case 103: return USER_ONLINE;
        case 104: return USER_OFFLINE;
        case 105: return SEND_NOTI_VIA_SOCKET;
        case 106: return SEND_NOTI_VIA_CLOUD;
        case 107: return SEND_NOTI_LIST_VIA_SOCKET;
        case 108: return SEND_NOTI_LIST_VIA_CLOUD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ActionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ActionType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ActionType>() {
            public ActionType findValueByNumber(int number) {
              return ActionType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.mservice.momo.msg.StatisticModels.getDescriptor().getEnumTypes().get(1);
    }

    private static final ActionType[] VALUES = values();

    public static ActionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ActionType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.mservice.momo.msg.ActionType)
  }

  public interface ActionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.mservice.momo.msg.ActionType type = 1;
    /**
     * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
     */
    com.mservice.momo.msg.StatisticModels.ActionType getType();

    // optional .com.mservice.momo.msg.Action.Channel channel = 2;
    /**
     * <code>optional .com.mservice.momo.msg.Action.Channel channel = 2;</code>
     */
    boolean hasChannel();
    /**
     * <code>optional .com.mservice.momo.msg.Action.Channel channel = 2;</code>
     */
    com.mservice.momo.msg.StatisticModels.Action.Channel getChannel();

    // optional uint32 phoneNumber = 3;
    /**
     * <code>optional uint32 phoneNumber = 3;</code>
     */
    boolean hasPhoneNumber();
    /**
     * <code>optional uint32 phoneNumber = 3;</code>
     */
    int getPhoneNumber();
  }
  /**
   * Protobuf type {@code com.mservice.momo.msg.Action}
   */
  public static final class Action extends
      com.google.protobuf.GeneratedMessage
      implements ActionOrBuilder {
    // Use Action.newBuilder() to construct.
    private Action(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Action(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Action defaultInstance;
    public static Action getDefaultInstance() {
      return defaultInstance;
    }

    public Action getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Action(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.mservice.momo.msg.StatisticModels.ActionType value = com.mservice.momo.msg.StatisticModels.ActionType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.mservice.momo.msg.StatisticModels.Action.Channel value = com.mservice.momo.msg.StatisticModels.Action.Channel.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                channel_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              phoneNumber_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mservice.momo.msg.StatisticModels.internal_static_com_mservice_momo_msg_Action_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mservice.momo.msg.StatisticModels.internal_static_com_mservice_momo_msg_Action_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mservice.momo.msg.StatisticModels.Action.class, com.mservice.momo.msg.StatisticModels.Action.Builder.class);
    }

    public static com.google.protobuf.Parser<Action> PARSER =
        new com.google.protobuf.AbstractParser<Action>() {
      public Action parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Action(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Action> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.mservice.momo.msg.Action.Channel}
     */
    public enum Channel
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>WEB = 1;</code>
       */
      WEB(0, 1),
      /**
       * <code>MOBILE = 2;</code>
       */
      MOBILE(1, 2),
      ;

      /**
       * <code>WEB = 1;</code>
       */
      public static final int WEB_VALUE = 1;
      /**
       * <code>MOBILE = 2;</code>
       */
      public static final int MOBILE_VALUE = 2;


      public final int getNumber() { return value; }

      public static Channel valueOf(int value) {
        switch (value) {
          case 1: return WEB;
          case 2: return MOBILE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Channel>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Channel>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Channel>() {
              public Channel findValueByNumber(int number) {
                return Channel.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.mservice.momo.msg.StatisticModels.Action.getDescriptor().getEnumTypes().get(0);
      }

      private static final Channel[] VALUES = values();

      public static Channel valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Channel(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.mservice.momo.msg.Action.Channel)
    }

    private int bitField0_;
    // required .com.mservice.momo.msg.ActionType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.mservice.momo.msg.StatisticModels.ActionType type_;
    /**
     * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
     */
    public com.mservice.momo.msg.StatisticModels.ActionType getType() {
      return type_;
    }

    // optional .com.mservice.momo.msg.Action.Channel channel = 2;
    public static final int CHANNEL_FIELD_NUMBER = 2;
    private com.mservice.momo.msg.StatisticModels.Action.Channel channel_;
    /**
     * <code>optional .com.mservice.momo.msg.Action.Channel channel = 2;</code>
     */
    public boolean hasChannel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.mservice.momo.msg.Action.Channel channel = 2;</code>
     */
    public com.mservice.momo.msg.StatisticModels.Action.Channel getChannel() {
      return channel_;
    }

    // optional uint32 phoneNumber = 3;
    public static final int PHONENUMBER_FIELD_NUMBER = 3;
    private int phoneNumber_;
    /**
     * <code>optional uint32 phoneNumber = 3;</code>
     */
    public boolean hasPhoneNumber() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 phoneNumber = 3;</code>
     */
    public int getPhoneNumber() {
      return phoneNumber_;
    }

    private void initFields() {
      type_ = com.mservice.momo.msg.StatisticModels.ActionType.USER_REGISTER;
      channel_ = com.mservice.momo.msg.StatisticModels.Action.Channel.WEB;
      phoneNumber_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, channel_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, phoneNumber_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, channel_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, phoneNumber_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mservice.momo.msg.StatisticModels.Action parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mservice.momo.msg.StatisticModels.Action parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mservice.momo.msg.StatisticModels.Action parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mservice.momo.msg.StatisticModels.Action parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mservice.momo.msg.StatisticModels.Action parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mservice.momo.msg.StatisticModels.Action parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mservice.momo.msg.StatisticModels.Action parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mservice.momo.msg.StatisticModels.Action parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mservice.momo.msg.StatisticModels.Action parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mservice.momo.msg.StatisticModels.Action parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mservice.momo.msg.StatisticModels.Action prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mservice.momo.msg.Action}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mservice.momo.msg.StatisticModels.ActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mservice.momo.msg.StatisticModels.internal_static_com_mservice_momo_msg_Action_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mservice.momo.msg.StatisticModels.internal_static_com_mservice_momo_msg_Action_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mservice.momo.msg.StatisticModels.Action.class, com.mservice.momo.msg.StatisticModels.Action.Builder.class);
      }

      // Construct using com.mservice.momo.msg.StatisticModels.Action.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.mservice.momo.msg.StatisticModels.ActionType.USER_REGISTER;
        bitField0_ = (bitField0_ & ~0x00000001);
        channel_ = com.mservice.momo.msg.StatisticModels.Action.Channel.WEB;
        bitField0_ = (bitField0_ & ~0x00000002);
        phoneNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mservice.momo.msg.StatisticModels.internal_static_com_mservice_momo_msg_Action_descriptor;
      }

      public com.mservice.momo.msg.StatisticModels.Action getDefaultInstanceForType() {
        return com.mservice.momo.msg.StatisticModels.Action.getDefaultInstance();
      }

      public com.mservice.momo.msg.StatisticModels.Action build() {
        com.mservice.momo.msg.StatisticModels.Action result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mservice.momo.msg.StatisticModels.Action buildPartial() {
        com.mservice.momo.msg.StatisticModels.Action result = new com.mservice.momo.msg.StatisticModels.Action(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.channel_ = channel_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.phoneNumber_ = phoneNumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mservice.momo.msg.StatisticModels.Action) {
          return mergeFrom((com.mservice.momo.msg.StatisticModels.Action)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mservice.momo.msg.StatisticModels.Action other) {
        if (other == com.mservice.momo.msg.StatisticModels.Action.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasChannel()) {
          setChannel(other.getChannel());
        }
        if (other.hasPhoneNumber()) {
          setPhoneNumber(other.getPhoneNumber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mservice.momo.msg.StatisticModels.Action parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mservice.momo.msg.StatisticModels.Action) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.mservice.momo.msg.ActionType type = 1;
      private com.mservice.momo.msg.StatisticModels.ActionType type_ = com.mservice.momo.msg.StatisticModels.ActionType.USER_REGISTER;
      /**
       * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
       */
      public com.mservice.momo.msg.StatisticModels.ActionType getType() {
        return type_;
      }
      /**
       * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
       */
      public Builder setType(com.mservice.momo.msg.StatisticModels.ActionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.mservice.momo.msg.StatisticModels.ActionType.USER_REGISTER;
        onChanged();
        return this;
      }

      // optional .com.mservice.momo.msg.Action.Channel channel = 2;
      private com.mservice.momo.msg.StatisticModels.Action.Channel channel_ = com.mservice.momo.msg.StatisticModels.Action.Channel.WEB;
      /**
       * <code>optional .com.mservice.momo.msg.Action.Channel channel = 2;</code>
       */
      public boolean hasChannel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.mservice.momo.msg.Action.Channel channel = 2;</code>
       */
      public com.mservice.momo.msg.StatisticModels.Action.Channel getChannel() {
        return channel_;
      }
      /**
       * <code>optional .com.mservice.momo.msg.Action.Channel channel = 2;</code>
       */
      public Builder setChannel(com.mservice.momo.msg.StatisticModels.Action.Channel value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.mservice.momo.msg.Action.Channel channel = 2;</code>
       */
      public Builder clearChannel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        channel_ = com.mservice.momo.msg.StatisticModels.Action.Channel.WEB;
        onChanged();
        return this;
      }

      // optional uint32 phoneNumber = 3;
      private int phoneNumber_ ;
      /**
       * <code>optional uint32 phoneNumber = 3;</code>
       */
      public boolean hasPhoneNumber() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 phoneNumber = 3;</code>
       */
      public int getPhoneNumber() {
        return phoneNumber_;
      }
      /**
       * <code>optional uint32 phoneNumber = 3;</code>
       */
      public Builder setPhoneNumber(int value) {
        bitField0_ |= 0x00000004;
        phoneNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 phoneNumber = 3;</code>
       */
      public Builder clearPhoneNumber() {
        bitField0_ = (bitField0_ & ~0x00000004);
        phoneNumber_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mservice.momo.msg.Action)
    }

    static {
      defaultInstance = new Action(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mservice.momo.msg.Action)
  }

  public interface GetNumberOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.mservice.momo.msg.ActionType type = 1;
    /**
     * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
     */
    com.mservice.momo.msg.StatisticModels.ActionType getType();

    // optional uint64 startDate = 2;
    /**
     * <code>optional uint64 startDate = 2;</code>
     */
    boolean hasStartDate();
    /**
     * <code>optional uint64 startDate = 2;</code>
     */
    long getStartDate();

    // optional uint64 endDate = 3;
    /**
     * <code>optional uint64 endDate = 3;</code>
     */
    boolean hasEndDate();
    /**
     * <code>optional uint64 endDate = 3;</code>
     */
    long getEndDate();
  }
  /**
   * Protobuf type {@code com.mservice.momo.msg.GetNumber}
   */
  public static final class GetNumber extends
      com.google.protobuf.GeneratedMessage
      implements GetNumberOrBuilder {
    // Use GetNumber.newBuilder() to construct.
    private GetNumber(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetNumber(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetNumber defaultInstance;
    public static GetNumber getDefaultInstance() {
      return defaultInstance;
    }

    public GetNumber getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetNumber(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.mservice.momo.msg.StatisticModels.ActionType value = com.mservice.momo.msg.StatisticModels.ActionType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              startDate_ = input.readUInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              endDate_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mservice.momo.msg.StatisticModels.internal_static_com_mservice_momo_msg_GetNumber_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mservice.momo.msg.StatisticModels.internal_static_com_mservice_momo_msg_GetNumber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mservice.momo.msg.StatisticModels.GetNumber.class, com.mservice.momo.msg.StatisticModels.GetNumber.Builder.class);
    }

    public static com.google.protobuf.Parser<GetNumber> PARSER =
        new com.google.protobuf.AbstractParser<GetNumber>() {
      public GetNumber parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetNumber(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetNumber> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.mservice.momo.msg.ActionType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.mservice.momo.msg.StatisticModels.ActionType type_;
    /**
     * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
     */
    public com.mservice.momo.msg.StatisticModels.ActionType getType() {
      return type_;
    }

    // optional uint64 startDate = 2;
    public static final int STARTDATE_FIELD_NUMBER = 2;
    private long startDate_;
    /**
     * <code>optional uint64 startDate = 2;</code>
     */
    public boolean hasStartDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 startDate = 2;</code>
     */
    public long getStartDate() {
      return startDate_;
    }

    // optional uint64 endDate = 3;
    public static final int ENDDATE_FIELD_NUMBER = 3;
    private long endDate_;
    /**
     * <code>optional uint64 endDate = 3;</code>
     */
    public boolean hasEndDate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint64 endDate = 3;</code>
     */
    public long getEndDate() {
      return endDate_;
    }

    private void initFields() {
      type_ = com.mservice.momo.msg.StatisticModels.ActionType.USER_REGISTER;
      startDate_ = 0L;
      endDate_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, startDate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, endDate_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, startDate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, endDate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mservice.momo.msg.StatisticModels.GetNumber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mservice.momo.msg.StatisticModels.GetNumber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mservice.momo.msg.StatisticModels.GetNumber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mservice.momo.msg.StatisticModels.GetNumber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mservice.momo.msg.StatisticModels.GetNumber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mservice.momo.msg.StatisticModels.GetNumber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mservice.momo.msg.StatisticModels.GetNumber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mservice.momo.msg.StatisticModels.GetNumber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mservice.momo.msg.StatisticModels.GetNumber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mservice.momo.msg.StatisticModels.GetNumber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mservice.momo.msg.StatisticModels.GetNumber prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mservice.momo.msg.GetNumber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mservice.momo.msg.StatisticModels.GetNumberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mservice.momo.msg.StatisticModels.internal_static_com_mservice_momo_msg_GetNumber_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mservice.momo.msg.StatisticModels.internal_static_com_mservice_momo_msg_GetNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mservice.momo.msg.StatisticModels.GetNumber.class, com.mservice.momo.msg.StatisticModels.GetNumber.Builder.class);
      }

      // Construct using com.mservice.momo.msg.StatisticModels.GetNumber.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.mservice.momo.msg.StatisticModels.ActionType.USER_REGISTER;
        bitField0_ = (bitField0_ & ~0x00000001);
        startDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        endDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mservice.momo.msg.StatisticModels.internal_static_com_mservice_momo_msg_GetNumber_descriptor;
      }

      public com.mservice.momo.msg.StatisticModels.GetNumber getDefaultInstanceForType() {
        return com.mservice.momo.msg.StatisticModels.GetNumber.getDefaultInstance();
      }

      public com.mservice.momo.msg.StatisticModels.GetNumber build() {
        com.mservice.momo.msg.StatisticModels.GetNumber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mservice.momo.msg.StatisticModels.GetNumber buildPartial() {
        com.mservice.momo.msg.StatisticModels.GetNumber result = new com.mservice.momo.msg.StatisticModels.GetNumber(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.startDate_ = startDate_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.endDate_ = endDate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mservice.momo.msg.StatisticModels.GetNumber) {
          return mergeFrom((com.mservice.momo.msg.StatisticModels.GetNumber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mservice.momo.msg.StatisticModels.GetNumber other) {
        if (other == com.mservice.momo.msg.StatisticModels.GetNumber.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasStartDate()) {
          setStartDate(other.getStartDate());
        }
        if (other.hasEndDate()) {
          setEndDate(other.getEndDate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mservice.momo.msg.StatisticModels.GetNumber parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mservice.momo.msg.StatisticModels.GetNumber) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.mservice.momo.msg.ActionType type = 1;
      private com.mservice.momo.msg.StatisticModels.ActionType type_ = com.mservice.momo.msg.StatisticModels.ActionType.USER_REGISTER;
      /**
       * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
       */
      public com.mservice.momo.msg.StatisticModels.ActionType getType() {
        return type_;
      }
      /**
       * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
       */
      public Builder setType(com.mservice.momo.msg.StatisticModels.ActionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.mservice.momo.msg.StatisticModels.ActionType.USER_REGISTER;
        onChanged();
        return this;
      }

      // optional uint64 startDate = 2;
      private long startDate_ ;
      /**
       * <code>optional uint64 startDate = 2;</code>
       */
      public boolean hasStartDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 startDate = 2;</code>
       */
      public long getStartDate() {
        return startDate_;
      }
      /**
       * <code>optional uint64 startDate = 2;</code>
       */
      public Builder setStartDate(long value) {
        bitField0_ |= 0x00000002;
        startDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 startDate = 2;</code>
       */
      public Builder clearStartDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        startDate_ = 0L;
        onChanged();
        return this;
      }

      // optional uint64 endDate = 3;
      private long endDate_ ;
      /**
       * <code>optional uint64 endDate = 3;</code>
       */
      public boolean hasEndDate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint64 endDate = 3;</code>
       */
      public long getEndDate() {
        return endDate_;
      }
      /**
       * <code>optional uint64 endDate = 3;</code>
       */
      public Builder setEndDate(long value) {
        bitField0_ |= 0x00000004;
        endDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 endDate = 3;</code>
       */
      public Builder clearEndDate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        endDate_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mservice.momo.msg.GetNumber)
    }

    static {
      defaultInstance = new GetNumber(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mservice.momo.msg.GetNumber)
  }

  public interface GetNumberReplyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.mservice.momo.msg.ActionType type = 1;
    /**
     * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
     */
    com.mservice.momo.msg.StatisticModels.ActionType getType();

    // optional uint64 number = 2;
    /**
     * <code>optional uint64 number = 2;</code>
     */
    boolean hasNumber();
    /**
     * <code>optional uint64 number = 2;</code>
     */
    long getNumber();
  }
  /**
   * Protobuf type {@code com.mservice.momo.msg.GetNumberReply}
   */
  public static final class GetNumberReply extends
      com.google.protobuf.GeneratedMessage
      implements GetNumberReplyOrBuilder {
    // Use GetNumberReply.newBuilder() to construct.
    private GetNumberReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetNumberReply(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetNumberReply defaultInstance;
    public static GetNumberReply getDefaultInstance() {
      return defaultInstance;
    }

    public GetNumberReply getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetNumberReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.mservice.momo.msg.StatisticModels.ActionType value = com.mservice.momo.msg.StatisticModels.ActionType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              number_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mservice.momo.msg.StatisticModels.internal_static_com_mservice_momo_msg_GetNumberReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mservice.momo.msg.StatisticModels.internal_static_com_mservice_momo_msg_GetNumberReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mservice.momo.msg.StatisticModels.GetNumberReply.class, com.mservice.momo.msg.StatisticModels.GetNumberReply.Builder.class);
    }

    public static com.google.protobuf.Parser<GetNumberReply> PARSER =
        new com.google.protobuf.AbstractParser<GetNumberReply>() {
      public GetNumberReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetNumberReply(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetNumberReply> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.mservice.momo.msg.ActionType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.mservice.momo.msg.StatisticModels.ActionType type_;
    /**
     * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
     */
    public com.mservice.momo.msg.StatisticModels.ActionType getType() {
      return type_;
    }

    // optional uint64 number = 2;
    public static final int NUMBER_FIELD_NUMBER = 2;
    private long number_;
    /**
     * <code>optional uint64 number = 2;</code>
     */
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 number = 2;</code>
     */
    public long getNumber() {
      return number_;
    }

    private void initFields() {
      type_ = com.mservice.momo.msg.StatisticModels.ActionType.USER_REGISTER;
      number_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, number_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, number_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mservice.momo.msg.StatisticModels.GetNumberReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mservice.momo.msg.StatisticModels.GetNumberReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mservice.momo.msg.StatisticModels.GetNumberReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mservice.momo.msg.StatisticModels.GetNumberReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mservice.momo.msg.StatisticModels.GetNumberReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mservice.momo.msg.StatisticModels.GetNumberReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mservice.momo.msg.StatisticModels.GetNumberReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mservice.momo.msg.StatisticModels.GetNumberReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mservice.momo.msg.StatisticModels.GetNumberReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mservice.momo.msg.StatisticModels.GetNumberReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mservice.momo.msg.StatisticModels.GetNumberReply prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mservice.momo.msg.GetNumberReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mservice.momo.msg.StatisticModels.GetNumberReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mservice.momo.msg.StatisticModels.internal_static_com_mservice_momo_msg_GetNumberReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mservice.momo.msg.StatisticModels.internal_static_com_mservice_momo_msg_GetNumberReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mservice.momo.msg.StatisticModels.GetNumberReply.class, com.mservice.momo.msg.StatisticModels.GetNumberReply.Builder.class);
      }

      // Construct using com.mservice.momo.msg.StatisticModels.GetNumberReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.mservice.momo.msg.StatisticModels.ActionType.USER_REGISTER;
        bitField0_ = (bitField0_ & ~0x00000001);
        number_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mservice.momo.msg.StatisticModels.internal_static_com_mservice_momo_msg_GetNumberReply_descriptor;
      }

      public com.mservice.momo.msg.StatisticModels.GetNumberReply getDefaultInstanceForType() {
        return com.mservice.momo.msg.StatisticModels.GetNumberReply.getDefaultInstance();
      }

      public com.mservice.momo.msg.StatisticModels.GetNumberReply build() {
        com.mservice.momo.msg.StatisticModels.GetNumberReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mservice.momo.msg.StatisticModels.GetNumberReply buildPartial() {
        com.mservice.momo.msg.StatisticModels.GetNumberReply result = new com.mservice.momo.msg.StatisticModels.GetNumberReply(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.number_ = number_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mservice.momo.msg.StatisticModels.GetNumberReply) {
          return mergeFrom((com.mservice.momo.msg.StatisticModels.GetNumberReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mservice.momo.msg.StatisticModels.GetNumberReply other) {
        if (other == com.mservice.momo.msg.StatisticModels.GetNumberReply.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasNumber()) {
          setNumber(other.getNumber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mservice.momo.msg.StatisticModels.GetNumberReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mservice.momo.msg.StatisticModels.GetNumberReply) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.mservice.momo.msg.ActionType type = 1;
      private com.mservice.momo.msg.StatisticModels.ActionType type_ = com.mservice.momo.msg.StatisticModels.ActionType.USER_REGISTER;
      /**
       * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
       */
      public com.mservice.momo.msg.StatisticModels.ActionType getType() {
        return type_;
      }
      /**
       * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
       */
      public Builder setType(com.mservice.momo.msg.StatisticModels.ActionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.mservice.momo.msg.ActionType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.mservice.momo.msg.StatisticModels.ActionType.USER_REGISTER;
        onChanged();
        return this;
      }

      // optional uint64 number = 2;
      private long number_ ;
      /**
       * <code>optional uint64 number = 2;</code>
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 number = 2;</code>
       */
      public long getNumber() {
        return number_;
      }
      /**
       * <code>optional uint64 number = 2;</code>
       */
      public Builder setNumber(long value) {
        bitField0_ |= 0x00000002;
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 number = 2;</code>
       */
      public Builder clearNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        number_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mservice.momo.msg.GetNumberReply)
    }

    static {
      defaultInstance = new GetNumberReply(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mservice.momo.msg.GetNumberReply)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mservice_momo_msg_Action_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mservice_momo_msg_Action_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mservice_momo_msg_GetNumber_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mservice_momo_msg_GetNumber_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mservice_momo_msg_GetNumberReply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mservice_momo_msg_GetNumberReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025StatisticModels.proto\022\025com.mservice.mo" +
      "mo.msg\"\246\001\n\006Action\022/\n\004type\030\001 \002(\0162!.com.ms" +
      "ervice.momo.msg.ActionType\0226\n\007channel\030\002 " +
      "\001(\0162%.com.mservice.momo.msg.Action.Chann" +
      "el\022\023\n\013phoneNumber\030\003 \001(\r\"\036\n\007Channel\022\007\n\003WE" +
      "B\020\001\022\n\n\006MOBILE\020\002\"`\n\tGetNumber\022/\n\004type\030\001 \002" +
      "(\0162!.com.mservice.momo.msg.ActionType\022\021\n" +
      "\tstartDate\030\002 \001(\004\022\017\n\007endDate\030\003 \001(\004\"Q\n\016Get" +
      "NumberReply\022/\n\004type\030\001 \002(\0162!.com.mservice" +
      ".momo.msg.ActionType\022\016\n\006number\030\002 \001(\004*\231\004\n",
      "\rSubActionType\022\034\n\030REGISTER_FROM_WEB_IN_D" +
      "AY\020\001\022\036\n\032REGISTER_FROM_PHONE_IN_DAY\020\002\022\035\n\031" +
      "NEW_WEB_USER_LOGIN_IN_DAY\020\003\022\037\n\033NEW_PHONE" +
      "_USER_LOGIN_IN_DAY\020\004\022\031\n\025USER_LOGIN_WEB_I" +
      "N_DAY\020\005\022\033\n\027USER_LOGIN_PHONE_IN_DAY\020\006\022\035\n\031" +
      "WEB_USER_HAS_TRANS_IN_DAY\020\007\022\037\n\033WEB_USER_" +
      "HAS_TRANS_IN_MONTH\020\010\022 \n\034MOBILE_USER_HAS_" +
      "TRANS_IN_DAY\020\t\022\"\n\036MOBILE_USER_HAS_TRANS_" +
      "IN_MONTH\020\n\022\036\n\032MAX_WEB_ONLINE_USER_IN_DAY" +
      "\020\014\022 \n\034MAX_PHONE_ONLINE_USER_IN_DAY\020\r\022\037\n\033",
      "SEND_NOTI_VIA_SOCKET_IN_DAY\020\016\022\036\n\032SEND_NO" +
      "TI_VIA_CLOUD_IN_DAY\020\017\022$\n SEND_NOTI_LIST_" +
      "VIA_SOCKET_IN_DAY\020\020\022#\n\037SEND_NOTI_LIST_VI" +
      "A_CLOUD_IN_DAY\020\021*\322\001\n\nActionType\022\021\n\rUSER_" +
      "REGISTER\020d\022\016\n\nUSER_LOGIN\020e\022\016\n\nUSER_TRANS" +
      "\020f\022\017\n\013USER_ONLINE\020g\022\020\n\014USER_OFFLINE\020h\022\030\n" +
      "\024SEND_NOTI_VIA_SOCKET\020i\022\027\n\023SEND_NOTI_VIA" +
      "_CLOUD\020j\022\035\n\031SEND_NOTI_LIST_VIA_SOCKET\020k\022" +
      "\034\n\030SEND_NOTI_LIST_VIA_CLOUD\020l"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_mservice_momo_msg_Action_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_mservice_momo_msg_Action_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mservice_momo_msg_Action_descriptor,
              new java.lang.String[] { "Type", "Channel", "PhoneNumber", });
          internal_static_com_mservice_momo_msg_GetNumber_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_mservice_momo_msg_GetNumber_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mservice_momo_msg_GetNumber_descriptor,
              new java.lang.String[] { "Type", "StartDate", "EndDate", });
          internal_static_com_mservice_momo_msg_GetNumberReply_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_mservice_momo_msg_GetNumberReply_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mservice_momo_msg_GetNumberReply_descriptor,
              new java.lang.String[] { "Type", "Number", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
